theme: jekyll-theme-minimal
title: Dost's Portfolio
locale: en_US
owner:
  name: Dost Karaahmetli
  avatar: bio-photo.jpeg
  email: dost.karaahmetli@shift-istanbul.com
  linkedin: https://www.linkedin.com/in/dostkaraahmetli/
  github: dostkaraahmetli
 
